advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'), name='basic_app')
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/',views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name = 'create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name = 'update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name = 'delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length = 256)
    principal = models.CharField(max_length = 256)
    location = models.CharField(max_length = 256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length = 256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name = 'students',on_delete = 'CASCADE')

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView,
                                ListView, DetailView,
                                CreateView,UpdateView,
                                DeleteView,)
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy
# Create your views here.


class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools' #returns a list named schools
    model = models.School
    #returns a list with the name school_list


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'
    #without context_object_name returns school (lowercase)

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School
    #expects template named school_form.html

class SchoolUpdateView(UpdateView):
    fields = ('name','principal',)
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    #reverse_lazy used since we dont want it evaluated completely when running the .py file
    #waits until actually called as a success
    success_url = reverse_lazy("basic_app:list") #Once view successfully deleted reverses to the 'list' url from apps url.py

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>

    <nav class= "navbar navbar-expand-sm navbar-light bg-light">
      <a class="navbarbrand" href= "{% url 'basic_app:list' %}">Schools</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>

</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{# needed for SchoolDeleteView to work #}
{% extends "basic_app/basic_app_base.html" %}
{% block body %}

<h1>Delete {{school.name}} ?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body %}
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    <h3>Students:</h3>
    <ol>
      {% for student in school_detail.students.all %}
      <p>{{student.name}} who is {{student.age}} years old</p>
      {% endfor %}
    </ol>

  </div>
  <div class="container">

    <p>
      <a class="btn btn-success" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    </p>

  </div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" class="btn btn-primary" value="Submit">
  </form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body %}

  <h1>Welcome to a list of all the schools</h1>
  <ol>
    {% for school in schools %}
      <h2>
        <li><a href="{{school.id}}">{{school.name}}</a></li>
      </h2>
    {% endfor %}
  </ol>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <style>
    .nav-item{
      margin: left;
    }
  </style>
  <body>

    <nav class= "navbar navbar-expand-sm navbar-light bg-light">
      <a class="navbarbrand" href= "{% url 'basic_app:list' %}">Schools</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body %}
  <div class="jumbotron">
    <h1>Homepage</h1>
  </div>
{% endblock %}